server:
  port: 8085
  
spring:
  application:
    name: CONFIG_SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TechnicalVarul/microservice_hrs_config
          clone-on-start: true
    
#Discovery client properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8061/eureka