#Server Properties
server:
  port: 8081
  

# Databse & Hibernate Properties 
spring:
  #MYSQL properties
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 101845
  application:
    name: USER-SERVICE
    
  # JPA properties   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
 #external configs
  config:
    import: optional:configserver:http://localhost:8085


#actuator properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
      
# Ressilience 4J
resilience4j:
  circuitbreaker:
    instances:
      hotelToRatingBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  retry:
    instances: 
      hotelToRatingRetry:
        max-attempts: 4
        wait-duration: 5s
        
  ratelimiter:
    instances:
      hotelRateLimiter:
        limit-for-period: 2
        limit-refresh-period: 4s
        timeout-duration: 2s
    
      
       